//! The bundled Progress Quest browser ruleset (`K.*` tables from the browser
//! client's `config.js`), captured verbatim so simulation never depends on a
//! mutable remote source.
//!
//! Each table below is an ordered, immutable `&'static [&'static str]` slice
//! reproducing the corresponding `K.*` JavaScript array exactly, including
//! entry order and the pipe (`|`)-delimited sub-fields the browser client
//! parses with its `Split` helper (e.g. `"Goblin|1|ear"` is
//! name|level|body-part). `K.Stats` is derived exactly as the browser derives
//! it: `K.PrimeStats` followed by `"HP Max"` and `"MP Max"`.

/// Where this ruleset snapshot was captured from.
pub const SOURCE_URL: &str = "https://progressquest.com/play/config.js";

/// The client/server protocol revision the source was serving as of capture
/// (matches [`crate::protocol::REVISION`]).
pub const SOURCE_REVISION: &str = "6";

/// SHA-256 of the captured `config.js` bytes, so a future ruleset refresh is
/// detectable even when `SOURCE_REVISION` is unchanged.
pub const SOURCE_CONTENT_SHA256: &str =
    "cc76f256057d6ddbf7010f1b94e59913b935b9980138ed5e800bdd1e5ff5ec4e";

/// The UTC date this snapshot was captured.
pub const CAPTURED_ON: &str = "2026-09-15";

/// `LevelUpTime`'s constants from the captured browser `config.js`.
pub const LEVEL_UP_BASE_MINUTES: u64 = 20;
pub const LEVEL_UP_GROWTH_NUMERATOR: u64 = 115;
pub const LEVEL_UP_GROWTH_DENOMINATOR: u64 = 100;

pub const TRAITS: &[&str] = &["Name", "Race", "Class", "Level"];

pub const NAME_PARTS: &[&[&str]] = &[
    &[
        "br", "cr", "dr", "fr", "gr", "j", "kr", "l", "m", "n", "pr", "", "", "", "r", "sh", "tr",
        "v", "wh", "x", "y", "z",
    ],
    &[
        "a", "a", "e", "e", "i", "i", "o", "o", "u", "u", "ae", "ie", "oo", "ou",
    ],
    &["b", "ck", "d", "g", "k", "m", "n", "p", "t", "v", "x", "z"],
];

pub const PRIME_STATS: &[&str] = &["STR", "CON", "DEX", "INT", "WIS", "CHA"];

pub const EQUIPS: &[&str] = &[
    "Weapon",
    "Shield",
    "Helm",
    "Hauberk",
    "Brassairts",
    "Vambraces",
    "Gauntlets",
    "Gambeson",
    "Cuisses",
    "Greaves",
    "Sollerets",
];

pub const SPELLS: &[&str] = &[
    "Slime Finger",
    "Rabbit Punch",
    "Hastiness",
    "Good Move",
    "Sadness",
    "Seasick",
    "Shoelaces",
    "Inoculate",
    "Cone of Annoyance",
    "Magnetic Orb",
    "Invisible Hands",
    "Revolting Cloud",
    "Aqueous Humor",
    "Spectral Miasma",
    "Clever Fellow",
    "Lockjaw",
    "History Lesson",
    "Hydrophobia",
    "Big Sister",
    "Cone of Paste",
    "Mulligan",
    "Nestor's Bright Idea",
    "Holy Batpole",
    "Tumor (Benign)",
    "Braingate",
    "Summon a Bitch",
    "Nonplus",
    "Animate Nightstand",
    "Eye of the Troglodyte",
    "Curse Name",
    "Dropsy",
    "Vitreous Humor",
    "Roger's Grand Illusion",
    "Covet",
    "Black Idaho",
    "Astral Miasma",
    "Spectral Oyster",
    "Acrid Hands",
    "Angioplasty",
    "Grognor's Big Day Off",
    "Tumor (Malignant)",
    "Animate Tunic",
    "Ursine Armor",
    "Holy Roller",
    "Tonsillectomy",
    "Curse Family",
    "Infinite Confusion",
];

pub const OFFENSE_ATTRIB: &[&str] = &[
    "Polished|+1",
    "Serrated|+1",
    "Heavy|+1",
    "Pronged|+2",
    "Steely|+2",
    "Vicious|+3",
    "Venomed|+4",
    "Stabbity|+4",
    "Dancing|+5",
    "Invisible|+6",
    "Vorpal|+7",
];

pub const DEFENSE_ATTRIB: &[&str] = &[
    "Studded|+1",
    "Banded|+2",
    "Gilded|+2",
    "Festooned|+3",
    "Holy|+4",
    "Cambric|+1",
    "Fine|+4",
    "Impressive|+5",
    "Custom|+3",
];

pub const SHIELDS: &[&str] = &[
    "Parasol|0",
    "Pie Plate|1",
    "Garbage Can Lid|2",
    "Buckler|3",
    "Plexiglass|4",
    "Fender|4",
    "Round Shield|5",
    "Carapace|5",
    "Scutum|6",
    "Propugner|6",
    "Kite Shield|7",
    "Pavise|8",
    "Tower Shield|9",
    "Baroque Shield|11",
    "Aegis|12",
    "Magnetic Field|18",
];

pub const ARMORS: &[&str] = &[
    "Lace|1",
    "Macrame|2",
    "Burlap|3",
    "Canvas|4",
    "Flannel|5",
    "Chamois|6",
    "Pleathers|7",
    "Leathers|8",
    "Bearskin|9",
    "Ringmail|10",
    "Scale Mail|12",
    "Chainmail|14",
    "Splint Mail|15",
    "Platemail|16",
    "ABS|17",
    "Kevlar|18",
    "Titanium|19",
    "Mithril Mail|20",
    "Diamond Mail|25",
    "Plasma|30",
];

pub const WEAPONS: &[&str] = &[
    "Stick|0",
    "Broken Bottle|1",
    "Shiv|1",
    "Sprig|1",
    "Oxgoad|1",
    "Eelspear|2",
    "Bowie Knife|2",
    "Claw Hammer|2",
    "Handpeen|2",
    "Andiron|3",
    "Hatchet|3",
    "Tomahawk|3",
    "Hackbarm|3",
    "Crowbar|4",
    "Mace|4",
    "Battleadze|4",
    "Leafmace|5",
    "Shortsword|5",
    "Longiron|5",
    "Poachard|5",
    "Baselard|5",
    "Whinyard|6",
    "Blunderbuss|6",
    "Longsword|6",
    "Crankbow|6",
    "Blibo|7",
    "Broadsword|7",
    "Kreen|7",
    "Warhammer|7",
    "Morning Star|8",
    "Pole-adze|8",
    "Spontoon|8",
    "Bastard Sword|9",
    "Peen-arm|9",
    "Culverin|10",
    "Lance|10",
    "Halberd|11",
    "Poleax|12",
    "Bandyclef|15",
];

pub const SPECIALS: &[&str] = &[
    "Diadem",
    "Festoon",
    "Gemstone",
    "Phial",
    "Tiara",
    "Scabbard",
    "Arrow",
    "Lens",
    "Lamp",
    "Hymnal",
    "Fleece",
    "Laurel",
    "Brooch",
    "Gimlet",
    "Cobble",
    "Albatross",
    "Brazier",
    "Bandolier",
    "Tome",
    "Garnet",
    "Amethyst",
    "Candelabra",
    "Corset",
    "Sphere",
    "Sceptre",
    "Ankh",
    "Talisman",
    "Orb",
    "Gammel",
    "Ornament",
    "Brocade",
    "Galoon",
    "Bijou",
    "Spangle",
    "Gimcrack",
    "Hood",
    "Vulpeculum",
];

pub const ITEM_ATTRIB: &[&str] = &[
    "Golden",
    "Gilded",
    "Spectral",
    "Astral",
    "Garlanded",
    "Precious",
    "Crafted",
    "Dual",
    "Filigreed",
    "Cruciate",
    "Arcane",
    "Blessed",
    "Reverential",
    "Lucky",
    "Enchanted",
    "Gleaming",
    "Grandiose",
    "Sacred",
    "Legendary",
    "Mythic",
    "Crystalline",
    "Austere",
    "Ostentatious",
    "One True",
    "Proverbial",
    "Fearsome",
    "Deadly",
    "Benevolent",
    "Unearthly",
    "Magnificent",
    "Iron",
    "Ormolu",
    "Puissant",
];

pub const ITEM_OFS: &[&str] = &[
    "Foreboding",
    "Foreshadowing",
    "Nervousness",
    "Happiness",
    "Torpor",
    "Danger",
    "Craft",
    "Silence",
    "Invisibility",
    "Rapidity",
    "Pleasure",
    "Practicality",
    "Hurting",
    "Joy",
    "Petulance",
    "Intrusion",
    "Chaos",
    "Suffering",
    "Extroversion",
    "Frenzy",
    "Sisu",
    "Solitude",
    "Punctuality",
    "Efficiency",
    "Comfort",
    "Patience",
    "Internment",
    "Incarceration",
    "Misapprehension",
    "Loyalty",
    "Envy",
    "Acrimony",
    "Worry",
    "Fear",
    "Awe",
    "Guile",
    "Prurience",
    "Fortune",
    "Perspicacity",
    "Domination",
    "Submission",
    "Fealty",
    "Hunger",
    "Despair",
    "Cruelty",
    "Grob",
    "Dignard",
    "Ra",
    "the Bone",
    "Diamonique",
    "Electrum",
    "Hydragyrum",
];

pub const BORING_ITEMS: &[&str] = &[
    "nail",
    "lunchpail",
    "sock",
    "I.O.U.",
    "cookie",
    "pint",
    "toothpick",
    "writ",
    "newspaper",
    "letter",
    "plank",
    "hat",
    "egg",
    "coin",
    "needle",
    "bucket",
    "ladder",
    "chicken",
    "twig",
    "dirtclod",
    "counterpane",
    "vest",
    "teratoma",
    "bunny",
    "rock",
    "pole",
    "carrot",
    "canoe",
    "inkwell",
    "hoe",
    "bandage",
    "trowel",
    "towel",
    "planter box",
    "anvil",
    "axle",
    "tuppence",
    "casket",
    "nosegay",
    "trinket",
    "credenza",
    "writ",
];

pub const MONSTERS: &[&str] = &[
    "Anhkheg|6|chitin",
    "Ant|0|antenna",
    "Ape|4|ass",
    "Baluchitherium|14|ear",
    "Beholder|10|eyestalk",
    "Black Pudding|10|saliva",
    "Blink Dog|4|eyelid",
    "Cub Scout|1|neckerchief",
    "Girl Scout|2|cookie",
    "Boy Scout|3|merit badge",
    "Eagle Scout|4|merit badge",
    "Bugbear|3|skin",
    "Bugboar|3|tusk",
    "Boogie|3|slime",
    "Camel|2|hump",
    "Carrion Crawler|3|egg",
    "Catoblepas|6|neck",
    "Centaur|4|rib",
    "Centipede|0|leg",
    "Cockatrice|5|wattle",
    "Couatl|9|wing",
    "Crayfish|0|antenna",
    "Demogorgon|53|tentacle",
    "Jubilex|17|gel",
    "Manes|1|tooth",
    "Orcus|27|wand",
    "Succubus|6|bra",
    "Vrock|8|neck",
    "Hezrou|9|leg",
    "Glabrezu|10|collar",
    "Nalfeshnee|11|tusk",
    "Marilith|7|arm",
    "Balor|8|whip",
    "Yeenoghu|25|flail",
    "Asmodeus|52|leathers",
    "Baalzebul|43|pants",
    "Barbed Devil|8|flame",
    "Bone Devil|9|hook",
    "Dispater|30|matches",
    "Erinyes|6|thong",
    "Geryon|30|cornucopia",
    "Malebranche|5|fork",
    "Ice Devil|11|snow",
    "Lemure|3|blob",
    "Pit Fiend|13|seed",
    "Ankylosaurus|9|tail",
    "Brontosaurus|30|brain",
    "Diplodocus|24|fin",
    "Elasmosaurus|15|neck",
    "Gorgosaurus|13|arm",
    "Iguanadon|6|thumb",
    "Megalosaurus|12|jaw",
    "Monoclonius|8|horn",
    "Pentasaurus|12|head",
    "Stegosaurus|18|plate",
    "Triceratops|16|horn",
    "Tyrannosaurus Rex|18|forearm",
    "Djinn|7|lamp",
    "Doppelganger|4|face",
    "Black Dragon|7|*",
    "Plaid Dragon|7|sporrin",
    "Blue Dragon|9|*",
    "Beige Dragon|9|*",
    "Brass Dragon|7|pole",
    "Tin Dragon|8|*",
    "Bronze Dragon|9|medal",
    "Chromatic Dragon|16|scale",
    "Copper Dragon|8|loafer",
    "Gold Dragon|8|filling",
    "Green Dragon|8|*",
    "Platinum Dragon|21|*",
    "Red Dragon|10|cocktail",
    "Silver Dragon|10|*",
    "White Dragon|6|tooth",
    "Dragon Turtle|13|shell",
    "Dryad|2|acorn",
    "Dwarf|1|drawers",
    "Eel|2|sashimi",
    "Efreet|10|cinder",
    "Sand Elemental|8|glass",
    "Bacon Elemental|10|bit",
    "Porn Elemental|12|lube",
    "Cheese Elemental|14|curd",
    "Hair Elemental|16|follicle",
    "Swamp Elf|1|lilypad",
    "Brown Elf|1|tusk",
    "Sea Elf|1|jerkin",
    "Ettin|10|fur",
    "Frog|0|leg",
    "Violet Fungi|3|spore",
    "Gargoyle|4|gravel",
    "Gelatinous Cube|4|jam",
    "Ghast|4|vomit",
    "Ghost|10|*",
    "Ghoul|2|muscle",
    "Humidity Giant|12|drops",
    "Beef Giant|11|steak",
    "Quartz Giant|10|crystal",
    "Porcelain Giant|9|fixture",
    "Rice Giant|8|grain",
    "Cloud Giant|12|condensation",
    "Fire Giant|11|cigarettes",
    "Frost Giant|10|snowman",
    "Hill Giant|8|corpse",
    "Stone Giant|9|hatchling",
    "Storm Giant|15|barometer",
    "Mini Giant|4|pompadour",
    "Gnoll|2|collar",
    "Gnome|1|hat",
    "Goblin|1|ear",
    "Grid Bug|1|carapace",
    "Jellyrock|9|seedling",
    "Beer Golem|15|foam",
    "Oxygen Golem|17|platelet",
    "Cardboard Golem|14|recycling",
    "Rubber Golem|16|ball",
    "Leather Golem|15|fob",
    "Gorgon|8|testicle",
    "Gray Ooze|3|gravy",
    "Green Slime|2|sample",
    "Griffon|7|nest",
    "Banshee|7|larynx",
    "Harpy|3|mascara",
    "Hell Hound|5|tongue",
    "Hippocampus|4|mane",
    "Hippogriff|3|egg",
    "Hobgoblin|1|patella",
    "Homunculus|2|fluid",
    "Hydra|8|gyrum",
    "Imp|2|tail",
    "Invisible Stalker|8|*",
    "Iron Peasant|3|chaff",
    "Jumpskin|3|shin",
    "Kobold|1|penis",
    "Leprechaun|1|wallet",
    "Leucrotta|6|hoof",
    "Lich|11|crown",
    "Lizard Man|2|tail",
    "Lurker|10|sac",
    "Manticore|6|spike",
    "Mastodon|12|tusk",
    "Medusa|6|eye",
    "Multicell|2|dendrite",
    "Pirate|1|booty",
    "Berserker|1|shirt",
    "Caveman|2|club",
    "Dervish|1|robe",
    "Merman|1|trident",
    "Mermaid|1|gills",
    "Mimic|9|hinge",
    "Mind Flayer|8|tentacle",
    "Minotaur|6|map",
    "Yellow Mold|1|spore",
    "Morkoth|7|teeth",
    "Mummy|6|gauze",
    "Naga|9|rattle",
    "Nebbish|1|belly",
    "Neo-Otyugh|11|organ ",
    "Nixie|1|webbing",
    "Nymph|3|hanky",
    "Ochre Jelly|6|nucleus",
    "Octopus|2|beak",
    "Ogre|4|talon",
    "Ogre Mage|5|apparel",
    "Orc|1|snout",
    "Otyugh|7|organ",
    "Owlbear|5|feather",
    "Pegasus|4|aileron",
    "Peryton|4|antler",
    "Piercer|3|tip",
    "Pixie|1|dust",
    "Man-o-war|3|tentacle",
    "Purple Worm|15|dung",
    "Quasit|3|tail",
    "Rakshasa|7|pajamas",
    "Rat|0|tail",
    "Remorhaz|11|protrusion",
    "Roc|18|wing",
    "Roper|11|twine",
    "Rot Grub|1|eggsac",
    "Rust Monster|5|shavings",
    "Satyr|5|hoof",
    "Sea Hag|3|wart",
    "Silkie|3|fur",
    "Shadow|3|silhouette",
    "Shambling Mound|10|mulch",
    "Shedu|9|hoof",
    "Shrieker|3|stalk",
    "Skeleton|1|clavicle",
    "Spectre|7|vestige",
    "Sphinx|10|paw",
    "Spider|0|web",
    "Sprite|1|can",
    "Stirge|1|proboscis",
    "Stun Bear|5|tooth",
    "Stun Worm|2|trode",
    "Su-monster|5|tail",
    "Sylph|3|thigh",
    "Titan|20|sandal",
    "Trapper|12|shag",
    "Treant|10|acorn",
    "Triton|3|scale",
    "Troglodyte|2|tail",
    "Troll|6|hide",
    "Umber Hulk|8|claw",
    "Unicorn|4|blood",
    "Vampire|8|pancreas",
    "Wight|4|lung",
    "Will-o'-the-Wisp|9|wisp",
    "Wraith|5|finger",
    "Wyvern|7|wing",
    "Xorn|7|jaw",
    "Yeti|4|fur",
    "Zombie|2|forehead",
    "Wasp|0|stinger",
    "Rat|1|tail",
    "Bunny|0|ear",
    "Moth|0|dust",
    "Beagle|0|collar",
    "Midge|0|corpse",
    "Ostrich|1|beak",
    "Billy Goat|1|beard",
    "Bat|1|wing",
    "Koala|2|heart",
    "Wolf|2|paw",
    "Whippet|2|collar",
    "Uruk|2|boot",
    "Poroid|4|node",
    "Moakum|8|frenum",
    "Fly|0|*",
    "Hogbird|3|curl",
    "Wolog|4|lemma",
];

pub const MON_MODS: &[&str] = &[
    "-4 fœtal *",
    "-4 dying *",
    "-3 crippled *",
    "-3 baby *",
    "-2 adolescent *",
    "-2 very sick *",
    "-1 lesser *",
    "-1 undernourished *",
    "+1 greater *",
    "+1 * Elder",
    "+2 war *",
    "+2 Battle-*",
    "+3 Were-*",
    "+3 undead *",
    "+4 giant *",
    "+4 * Rex",
];

pub const OFFENSE_BAD: &[&str] = &[
    "Dull|-2",
    "Tarnished|-1",
    "Rusty|-3",
    "Padded|-5",
    "Bent|-4",
    "Mini|-4",
    "Rubber|-6",
    "Nerf|-7",
    "Unbalanced|-2",
];

pub const DEFENSE_BAD: &[&str] = &[
    "Holey|-1",
    "Patched|-1",
    "Threadbare|-2",
    "Faded|-1",
    "Rusty|-3",
    "Motheaten|-3",
    "Mildewed|-2",
    "Torn|-3",
    "Dented|-3",
    "Cursed|-5",
    "Plastic|-4",
    "Cracked|-4",
    "Warped|-3",
    "Corroded|-3",
];

pub const RACES: &[&str] = &[
    "Half Orc|HP Max",
    "Half Man|CHA",
    "Half Halfling|DEX",
    "Double Hobbit|STR",
    "Hob-Hobbit|DEX,CON",
    "Low Elf|CON",
    "Dung Elf|WIS",
    "Talking Pony|MP Max,INT",
    "Gyrognome|DEX",
    "Lesser Dwarf|CON",
    "Crested Dwarf|CHA",
    "Eel Man|DEX",
    "Panda Man|CON,STR",
    "Trans-Kobold|WIS",
    "Enchanted Motorcycle|MP Max",
    "Will o' the Wisp|WIS",
    "Battle-Finch|DEX,INT",
    "Double Wookiee|STR",
    "Skraeling|WIS",
    "Demicanadian|CON",
    "Land Squid|STR,HP Max",
];

pub const KLASSES: &[&str] = &[
    "Ur-Paladin|WIS,CON",
    "Voodoo Princess|INT,CHA",
    "Robot Monk|STR",
    "Mu-Fu Monk|DEX",
    "Mage Illusioner|INT,MP Max",
    "Shiv-Knight|DEX",
    "Inner Mason|CON",
    "Fighter/Organist|CHA,STR",
    "Puma Burgular|DEX",
    "Runeloremaster|WIS",
    "Hunter Strangler|DEX,INT",
    "Battle-Felon|STR",
    "Tickle-Mimic|WIS,INT",
    "Slow Poisoner|CON",
    "Bastard Lunatic|CON",
    "Lowling|WIS",
    "Birdrider|WIS",
    "Vermineer|INT",
];

pub const TITLES: &[&str] = &[
    "Mr.", "Mrs.", "Sir", "Sgt.", "Ms.", "Captain", "Chief", "Admiral", "Saint",
];

pub const IMPRESSIVE_TITLES: &[&str] = &[
    "King",
    "Queen",
    "Lord",
    "Lady",
    "Viceroy",
    "Mayor",
    "Prince",
    "Princess",
    "Chief",
    "Boss",
    "Archbishop",
    "Chancellor",
    "Baroness",
    "Inquistor",
];
/// `K.PrimeStats` followed by `"HP Max"` and `"MP Max"`, matching the
/// browser's `K.Stats = K.PrimeStats.slice(0).concat(["HP Max","MP Max"])`.
pub const STATS: &[&str] = &["STR", "CON", "DEX", "INT", "WIS", "CHA", "HP Max", "MP Max"];

/// A reference to the bundled browser ruleset, selected explicitly by
/// simulation callers so a later ruleset revision cannot silently change an
/// existing run's outcome. All fields are `&'static` slices into the
/// compiled-in tables above, so a `Ruleset` value is immutable and cheap to
/// copy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Ruleset {
    pub source: &'static str,
    pub revision: &'static str,
    pub content_sha256: &'static str,
    pub level_up_base_minutes: u64,
    pub level_up_growth_numerator: u64,
    pub level_up_growth_denominator: u64,
    pub traits: &'static [&'static str],
    pub name_parts: &'static [&'static [&'static str]],
    pub prime_stats: &'static [&'static str],
    pub stats: &'static [&'static str],
    pub equips: &'static [&'static str],
    pub spells: &'static [&'static str],
    pub offense_attrib: &'static [&'static str],
    pub defense_attrib: &'static [&'static str],
    pub shields: &'static [&'static str],
    pub armors: &'static [&'static str],
    pub weapons: &'static [&'static str],
    pub specials: &'static [&'static str],
    pub item_attrib: &'static [&'static str],
    pub item_ofs: &'static [&'static str],
    pub boring_items: &'static [&'static str],
    pub monsters: &'static [&'static str],
    pub mon_mods: &'static [&'static str],
    pub offense_bad: &'static [&'static str],
    pub defense_bad: &'static [&'static str],
    pub races: &'static [&'static str],
    pub klasses: &'static [&'static str],
    pub titles: &'static [&'static str],
    pub impressive_titles: &'static [&'static str],
}

/// The single bundled ruleset revision. Simulation callers select it
/// explicitly (rather than `advance` reaching for it implicitly) so a future
/// bundled revision requires an explicit caller choice.
pub const BUNDLED: Ruleset = Ruleset {
    source: SOURCE_URL,
    revision: SOURCE_REVISION,
    content_sha256: SOURCE_CONTENT_SHA256,
    level_up_base_minutes: LEVEL_UP_BASE_MINUTES,
    level_up_growth_numerator: LEVEL_UP_GROWTH_NUMERATOR,
    level_up_growth_denominator: LEVEL_UP_GROWTH_DENOMINATOR,
    traits: TRAITS,
    name_parts: NAME_PARTS,
    prime_stats: PRIME_STATS,
    stats: STATS,
    equips: EQUIPS,
    spells: SPELLS,
    offense_attrib: OFFENSE_ATTRIB,
    defense_attrib: DEFENSE_ATTRIB,
    shields: SHIELDS,
    armors: ARMORS,
    weapons: WEAPONS,
    specials: SPECIALS,
    item_attrib: ITEM_ATTRIB,
    item_ofs: ITEM_OFS,
    boring_items: BORING_ITEMS,
    monsters: MONSTERS,
    mon_mods: MON_MODS,
    offense_bad: OFFENSE_BAD,
    defense_bad: DEFENSE_BAD,
    races: RACES,
    klasses: KLASSES,
    titles: TITLES,
    impressive_titles: IMPRESSIVE_TITLES,
};

impl Default for Ruleset {
    /// The only selectable ruleset today is the bundled snapshot.
    fn default() -> Self {
        BUNDLED
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_lengths_match_the_captured_browser_source() {
        assert_eq!(TRAITS.len(), 4);
        assert_eq!(NAME_PARTS.len(), 3);
        assert_eq!(PRIME_STATS.len(), 6);
        assert_eq!(STATS.len(), 8);
        assert_eq!(EQUIPS.len(), 11);
        assert_eq!(SPELLS.len(), 47);
        assert_eq!(OFFENSE_ATTRIB.len(), 11);
        assert_eq!(DEFENSE_ATTRIB.len(), 9);
        assert_eq!(SHIELDS.len(), 16);
        assert_eq!(ARMORS.len(), 20);
        assert_eq!(WEAPONS.len(), 39);
        assert_eq!(SPECIALS.len(), 37);
        assert_eq!(ITEM_ATTRIB.len(), 33);
        assert_eq!(ITEM_OFS.len(), 52);
        assert_eq!(BORING_ITEMS.len(), 42);
        assert_eq!(MONSTERS.len(), 232);
        assert_eq!(MON_MODS.len(), 16);
        assert_eq!(OFFENSE_BAD.len(), 9);
        assert_eq!(DEFENSE_BAD.len(), 14);
        assert_eq!(RACES.len(), 21);
        assert_eq!(KLASSES.len(), 18);
        assert_eq!(TITLES.len(), 9);
        assert_eq!(IMPRESSIVE_TITLES.len(), 14);
    }

    #[test]
    fn preserves_pipe_delimited_sub_fields_and_source_order() {
        assert_eq!(MONSTERS[0], "Anhkheg|6|chitin");
        assert_eq!(MONSTERS[MONSTERS.len() - 1], "Wolog|4|lemma");
        assert_eq!(WEAPONS[0], "Stick|0");
        assert_eq!(SPELLS[0], "Slime Finger");
        assert_eq!(SPELLS[SPELLS.len() - 1], "Infinite Confusion");
    }

    #[test]
    fn bundled_ruleset_is_immutable_and_explicitly_selected() {
        // `Ruleset` is `Copy`/`Eq` over `&'static` data: two independently
        // obtained values are identical and neither can mutate the shared
        // tables, so a simulation run's selected ruleset cannot change under
        // it.
        let a = BUNDLED;
        let b = Ruleset::default();
        assert_eq!(a, b);
        assert_eq!(a.revision, "6");
        assert_eq!(a.content_sha256, SOURCE_CONTENT_SHA256);
    }
}
